name: Run tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push
  #push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11,3.12"]

    steps:
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Thailand"
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install requirements.txt && pytest-md && pytest-emoji
      - name: Run pytest
        uses: pavelzw/pytest-action@v2
        with:
          emoji: true
          verbose: false
          job-summary: true
